service: dio-serverless-project
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:us-east-1:260059209081:table/ItemTableNew

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/lambdas/items/insertItem.handler
    events:
      - httpApi:
          path: /items
          method: post
  getItens:
    handler: src/lambdas/items/getItens.handler
    events:
      - httpApi:
          path: /items
          method: get
  getItem:
    handler: src/lambdas/items/getItem.handler
    events:
      - httpApi:
          path: /items/{id}
          method: get
  updateItem:
    handler: src/lambdas/items/updateItem.handler
    events:
      - httpApi:
          path: /items/{id}
          method: put

resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
